### PR TITLE
Add IBDesignable and IBInspectable

### PR DESCRIPTION
**Pull request by LeeroyDing**
Supporting them will make life with storyboards easier.

This is a very simple approach without modifying anything. Any discussion is welcome.

### CODE REVIEW

**Comment by ninjinkun** [comment]
I tried this patch through Carthage. But it didn't work because IB annotations were striped from framework interoperability header `GradientView-Swift.h`. It seems Swift's bug. Same problems are here  https://github.com/Carthage/Carthage/issues/335 . 
This patch maybe works without framework (add to project directly).

**Comment by soffes** [comment]
Thanks! Can you remove all of those white space changes from your PR? Guessing those weren't on purpose.

@ninjinkun bummer. I guess people can just use submodules if they want to use this until this is fixed.

**Comment by LeeroyDing** [comment]
I reversed the whitespace changes but kept one that changed the indention from white spaces to tabs, which stays in sync with other lines. No idea why this line was indented with space.

I wish Apple would make IBInspectable arrays possible, so it would be much more useful.

**Comment by soffes** [comment]
Looks good! Thanks!

**Pull request merged**
