### PR TITLE
Better control for radial gradients

### PR DESCRIPTION
**Pull request by jbergen**
Makes more complex radial gradients possible with four new variables:
- `radialStartAnchor: CGPoint`
- `radialStartRadius: CGFloat`
- `radialEndAnchor: CGPoint`
- `radialEndRadius: CGFloat`

Not setting these variables will keep existing behavior 🌈

**_Thanks for the great work on this!!**_

### CODE REVIEW

**Comment by soffes** [comment]
What if this was a struct with anchor and radius ;)

**Comment by jbergen** [comment]
updated commit with a struct as suggested :+1:

lmk if you plan on merging and I can squash these commits first!

**Comment by soffes** [comment]
Nice! I think we can come up with a better than than `RadialGradientAttributes` though. I wonder if @hyperspacemark has any ideas :)

**Comment by GabrielCartier** [comment]
Any news on this? We kind of have the same need.

**Comment by soffes** [comment]
Can you rebase master @jbergen?

**Pull request closed without merging**
